#! /bin/sh

set -e

INSTALL_PREFIX=/usr/lib/octopus
echo "$INSTALL_PREFIX/lib" > /etc/ld.so.conf.d/octopus.conf
ldconfig

ln -s $INSTALL_PREFIX/bin/octopus /usr/bin/octopus
ln -s $INSTALL_PREFIX/bin/octopus-debug /usr/bin/octopus-debug
ln -s $INSTALL_PREFIX/bin/octopus-ctl /usr/bin/octopus-ctl
ln -s $INSTALL_PREFIX/bin/octopus-ctl /usr/bin/pg_ctl
ln -s $INSTALL_PREFIX/bin/octopus-init /usr/bin/octopus-init
ln -s $INSTALL_PREFIX/bin/psql /usr/bin/psql
ln -s $INSTALL_PREFIX/bin/psql /usr/bin/octopus
ln -s $INSTALL_PREFIX/bin/octopus-config /usr/bin/pg_config
ln -s $INSTALL_PREFIX/bin/octopus-dump /usr/bin/octopus-dump
ln -s $INSTALL_PREFIX/bin/octopus-dumpall /usr/bin/octopus-dumpall
ln -s $INSTALL_PREFIX/bin/octopus-restore /usr/bin/octopus-restore

echo "
    ____  _            ___            ____  ____
   / __ \(_)___  ___  / (_)___  ___  / __ \/ __ )
  / /_/ / / __ \/ _ \/ / / __ \/ _ \/ / / / __  |
 / ____/ / /_/ /  __/ / / / / /  __/ /_/ / /_/ /
/_/   /_/ .___/\___/_/_/_/ /_/\___/_____/_____/
       /_/

Octopus successfully installed. To get started, initialize a
database directory:

octopus-init -D <data directory>

where <data directory> is a nonexistent directory where you'd
like all of your database files to live.

You can find the Octopus documentation at:

http://docs.octopus.com
"
