#! /bin/bash

INSTALL_PREFIX=/usr/local/lib/octopus

ln -s $INSTALL_PREFIX/bin/octopus /usr/local/bin/octopus
ln -s $INSTALL_PREFIX/bin/octopus-debug /usr/local/bin/octopus-debug
ln -s $INSTALL_PREFIX/bin/octopus-ctl /usr/local/bin/octopus-ctl
ln -s $INSTALL_PREFIX/bin/octopus-ctl /usr/local/bin/pg_ctl
ln -s $INSTALL_PREFIX/bin/octopus-init /usr/local/bin/octopus-init
ln -s $INSTALL_PREFIX/bin/psql /usr/local/bin/psql
ln -s $INSTALL_PREFIX/bin/psql /usr/local/bin/octopus
ln -s $INSTALL_PREFIX/bin/octopus-config /usr/local/bin/pg_config
ln -s $INSTALL_PREFIX/bin/octopus-dump /usr/local/bin/octopus-dump
ln -s $INSTALL_PREFIX/bin/octopus-dumpall /usr/local/bin/octopus-dumpall
ln -s $INSTALL_PREFIX/bin/octopus-restore /usr/local/bin/octopus-restore

rm $INSTALL_PREFIX/postinst

echo "
    ____  _            ___            ____  ____
   / __ \(_)___  ___  / (_)___  ___  / __ \/ __ )
  / /_/ / / __ \/ _ \/ / / __ \/ _ \/ / / / __  |
 / ____/ / /_/ /  __/ / / / / /  __/ /_/ / /_/ /
/_/   /_/ .___/\___/_/_/_/ /_/\___/_____/_____/
       /_/

Octopus successfully installed. To get started, initialize a
database directory:

octopus-init -D <data directory>

where <data directory> is a nonexistent directory where you'd
like all of your database files to live.

You can find the Octopus documentation at:

http://docs.octopus.com
"
